server:
  port: 9192

spring:
  datasource:
    username: root
    password: Aliza
    url: jdbc:mysql://localhost:3307/React_Java
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true
